### ISSUE TITLE
Martian Integration Discussion

### ISSUE THREAD

**Issue by zhaomengru2015** [KeystoneHQ/Keystone-developer-hub#7]
Regarding the [account address generation and authentication key generation](https://github.com/KeystoneHQ/Keystone-developer-hub/issues/6), we have some other questions about the integration.

## Questions

1. In my understand, currently in Martian, when importing wallet, if the account does not exist on Aptos blockchains(according to the current account searching logic in Martian), this account can not be imported to Martian wallet, it means that it's impossible to import Keystone's newly created account into Martian.  Could we update this logic so that newly created account can be imported?

**Comment by aaronisme** [comment]
close for now
